apiVersion: v1
kind: Service
metadata:
  name: {{ include "apisix.fullname" . }}
  labels:
    {{- include "apisix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "apisix.selectorLabels" . | nindent 4 }}
